---
- name: Start MariaDB
  service: name={{ mariadb_service_name }} state=started

- name: Stop MariaDB
  service: name={{ mariadb_service_name }} state=stopped

- name: Restart MariaDB
  service: name={{ mariadb_service_name }} state=restarted

- name: Reload MariaDB
  service: name={{ mariadb_service_name }} state=reloaded
