---
- name: Starting MariaDB
  service:
    name: '{{ mariadb_service_name }}'
    state: started

- name: Stopping MariaDB
  service:
    name: '{{ mariadb_service_name }}'
    state: stopped

- name: Restarting MariaDB
  service:
    name: '{{ mariadb_service_name }}'
    state: restarted